clear all;
clc;
[y,Fs] = audioread('Apaga0.wav');
Mn = Mn(y,Fs,2);
Zn = Zn(y,Fs,2);
Ms = Mn(1:10);
Zs = Zn(1:10);
[mediaMs,sigmaMs] = dispersion(Ms);
[mediaZs,sigmaZs] = dispersion(Zs);
UmbSupEnrg = 0.5*max(Mn);
UmbInfEnrg = mediaMs+2*sigmaMs;
UmbCruCero = mediaZs+2*sigmaZs;
ln = lnRab(Mn,UmbSupEnrg);
le = leRab(Mn,UmbInfEnrg,ln);
lz = lzRab(Zn,UmbCruCero,le);
fprintf('UmbSupEnrg=%d\nUmbInfEnrg=%d\nUmbCruCero=%d\n',UmbSupEnrg,UmbInfEnrg,UmbCruCero);
fprintf('le=%d\nln=%d\nlz=%d\nValores=%d,%d\n',le,ln,lz,Mn(le),Mn(ln));
close all;
figure,subplot(2,1,1),plot(y),title('Audio'),hold on, line([lz*128,lz*128],[min(y),max(y)],'color',[1 0 0]),subplot(2,1,2),plot(Mn),hold on,line([lz,lz],[min(Mn),max(Mn)],'color',[1 0 0]),title('Mn (Amplitudes promedio)');
figure,subplot(2,1,1),plot(y),title('Audio'),hold on, line([lz*128,lz*128],[min(y),max(y)],'color',[1 0 0]),subplot(2,1,2),plot(Zn),hold on, line([lz,lz],[min(Zn),max(Zn)],'color',[1 0 0]),title('Zn (Cruces por 0 Promedio)');